{% set name = "fastjet-cxx" %}
{% set version = "3.4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://gitlab.com/fastjet/fastjet/-/archive/fastjet-{{ version }}/fastjet-fastjet-{{ version }}.tar.gz
    sha256: 8ce8b9be5cd0fba4f2fe914871eabe259dfa7524edf925635e20072cde2ae6a8
    patches:
      - 0001-use-conda-forge-siscone-for-plugin.patch

build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage('fastjet-cxx', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - automake
    - libtool
    - make
    - pkg-config
    - gnuconfig
    - cgal
    - siscone  # [build_platform != target_platform]
  host:
    - siscone
  run:
    - siscone

test:
  source_files:
    - example/fastjet_example.cc
    - example/fastjet_areas.cc
    - example/01-basic.cc
    - example/02-jetdef.cc
    - example/03-plugin.cc
    - example/04-constituents.cc
    - example/05-eplus_eminus.cc
    - example/06-area.cc
    - example/07-subtraction.cc
    - example/08-selector.cc
    - example/09-user_info.cc
    - example/10-subjets.cc
    - example/11-filter.cc
    - example/12-boosted_higgs.cc
    - example/13-boosted_top.cc
    - example/14-groomers.cc
    - example/data/single-event.dat
    - example/data/single-ee-event.dat
    - example/data/Pythia-Zp2jets-lhc-pileup-1ev.dat
    - example/data/Pythia-dijet-ptmin100-lhc-pileup-1ev.dat
    - example/data/HZ-event-Hmass115.dat
    - example/data/boosted_top_event.dat
  requires:
    - {{ compiler('cxx') }}
  commands:
    - test -f $PREFIX/bin/fastjet-config
    - test -f $PREFIX/lib/libfastjet${SHLIB_EXT}
    - test -f $PREFIX/lib/libfastjetplugins${SHLIB_EXT}
    - test -f $PREFIX/lib/libfastjettools${SHLIB_EXT}
    - test -d $PREFIX/include/fastjet
    - test -d $PREFIX/include/fastjet/internal
    - test -d $PREFIX/include/fastjet/tools

    - fastjet-config --help
    - fastjet-config --version
    - fastjet-config --prefix
    - fastjet-config --cxxflags
    - fastjet-config --libs
    - fastjet-config --list-plugins
    - fastjet-config --libs --plugins
    - fastjet-config --config
    - fastjet-config --pythonpath

    - cd example/
    - $CXX fastjet_example.cc -o fastjet_example $CXXFLAGS $LDFLAGS -lfastjet
    - ./fastjet_example < data/single-event.dat
    - $CXX fastjet_areas.cc -o fastjet_areas $CXXFLAGS $LDFLAGS -lfastjet
    - ./fastjet_areas < data/single-event.dat
    - $CXX 01-basic.cc -o 01-basic $CXXFLAGS $LDFLAGS -lfastjet
    - ./01-basic < data/single-event.dat
    - $CXX 02-jetdef.cc -o 02-jetdef $CXXFLAGS $LDFLAGS -lfastjet
    - ./02-jetdef < data/single-event.dat
    - $CXX 03-plugin.cc -o 03-plugin $CXXFLAGS $LDFLAGS -lfastjet -lfastjetplugins
    - ./03-plugin < data/single-event.dat
    - rm ./03-plugin
    - $CXX 03-plugin.cc -o 03-plugin $CXXFLAGS $LDFLAGS $(fastjet-config --libs --plugins)
    - ./03-plugin < data/single-event.dat
    - $CXX 04-constituents.cc -o 04-constituents $CXXFLAGS $LDFLAGS -lfastjet
    - ./04-constituents < data/single-event.dat
    - $CXX 05-eplus_eminus.cc -o 05-eplus_eminus $CXXFLAGS $LDFLAGS -lfastjet
    - ./05-eplus_eminus < data/single-ee-event.dat
    - $CXX 06-area.cc -o 06-area $CXXFLAGS $LDFLAGS -lfastjet
    - ./06-area < data/single-event.dat
    - $CXX 07-subtraction.cc -o 07-subtraction $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
    - ./07-subtraction < data/Pythia-Zp2jets-lhc-pileup-1ev.dat
    - $CXX 08-selector.cc -o 08-selector $CXXFLAGS $LDFLAGS -lfastjet
    - ./08-selector < data/single-event.dat
    - $CXX 09-user_info.cc -o 09-user_info $CXXFLAGS $LDFLAGS -lfastjet
    - ./09-user_info < data/Pythia-dijet-ptmin100-lhc-pileup-1ev.dat
    - $CXX 10-subjets.cc -o 10-subjets $CXXFLAGS $LDFLAGS -lfastjet
    - ./10-subjets < data/single-event.dat
    - $CXX 11-filter.cc -o 11-filter $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
    - ./11-filter < data/single-event.dat
    - $CXX 12-boosted_higgs.cc -o 12-boosted_higgs $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
    - ./12-boosted_higgs < data/HZ-event-Hmass115.dat
    - $CXX 13-boosted_top.cc -o 13-boosted_top $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
    - ./13-boosted_top < data/boosted_top_event.dat
    - $CXX 14-groomers.cc -o 14-groomers $CXXFLAGS $LDFLAGS -lfastjettools -lfastjet
    - ./14-groomers < data/boosted_top_event.dat

about:
  home: https://gitlab.com/fastjet/fastjet
  summary: 'FastJet: jet finding in pp and e+e- collisions'
  description: |
    FastJet is a software package for jet finding in pp and e+e- collisions.
    It includes fast native implementations of many sequential recombination
    clustering algorithms, plugins for access to a range of cone jet finders
    and tools for advanced jet manipulation.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  dev_url: https://gitlab.com/fastjet/fastjet
  doc_url: https://fastjet.fr/

extra:
  recipe-maintainers:
    - kratsg
    - matthewfeickert
